version: '2'

volumes:
  orderer.org0.com:

networks:
  certification:

services:
  zookeeper1.org0.com:
    container_name: zookeeper1.org0.com
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper-base
    networks:
      - certification

  zookeeper2.org0.com:
    container_name: zookeeper2.org0.com
    extends:
      file: ../base/kafka-base.yaml
      service: zookeeper-base
    networks:
      - certification

  kafka1.org0.com:
    container_name: kafka1.org0.com
    extends:
      file: ../base/kafka-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.org0.com:32181,zookeeper2.org0.com:32181
    depends_on:
      - zookeeper1.org0.com
      - zookeeper2.org0.com
    networks:
      - certification

  kafka2.org0.com:
    container_name: kafka2.org0.com
    extends:
      file: ../base/kafka-base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1.org0.com:32181,zookeeper2.org0.com:32181
    depends_on:
      - zookeeper1.org0.com
      - zookeeper2.org0.com
    networks:
      - certification

  orderer.org0.com:
    container_name: orderer.org0.com
    extends:
      file: ../base/orderer-base.yaml
      service: orderer-base
    volumes:
      - /var/run/:/host/var/run/
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/org0.com/orderers/orderer.org0.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/org0.com/orderers/orderer.org0.com/tls:/var/hyperledger/orderer/tls
      - orderer.org0.com:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
    depends_on:
      - kafka1.org0.com
      - kafka2.org0.com
    networks:
      - certification
      