OrdererOrgs:
  - Name: Orderer
    Domain: org0.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2

  - Name: Org2
    Domain: org2.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2